version: "3.9"

services:
  tradebert:
    container_name: tradebert
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - /opt/bots/Tradebert:/usr/src/app
    network_mode: host 
    working_dir: /usr/src/app
    restart: unless-stopped
